export type ZodiacSign = {
  name: string;
  symbol: string;
  element: string;
  dates: string;
  traits: string[];
  compatibleSigns: string[];
  luckyNumber: number;
  color: string;
};

export const zodiacSigns: Record<string, ZodiacSign> = {
  aries: {
    name: "Aries",
    symbol: "♈",
    element: "Fire",
    dates: "March 21 - April 19",
    traits: ["Courageous", "Determined", "Confident", "Enthusiastic"],
    compatibleSigns: ["Leo", "Sagittarius", "Gemini", "Aquarius"],
    luckyNumber: 7,
    color: "text-red-400",
  },
  taurus: {
    name: "Taurus",
    symbol: "♉",
    element: "Earth",
    dates: "April 20 - May 20",
    traits: ["Reliable", "Patient", "Practical", "Devoted"],
    compatibleSigns: ["Virgo", "Capricorn", "Cancer", "Pisces"],
    luckyNumber: 6,
    color: "text-green-400",
  },
  gemini: {
    name: "Gemini",
    symbol: "♊",
    element: "Air",
    dates: "May 21 - June 20",
    traits: ["Gentle", "Affectionate", "Curious", "Adaptable"],
    compatibleSigns: ["Libra", "Aquarius", "Aries", "Leo"],
    luckyNumber: 5,
    color: "text-yellow-400",
  },
  cancer: {
    name: "Cancer",
    symbol: "♋",
    element: "Water",
    dates: "June 21 - July 22",
    traits: ["Tenacious", "Imaginative", "Loyal", "Emotional"],
    compatibleSigns: ["Scorpio", "Pisces", "Taurus", "Virgo"],
    luckyNumber: 2,
    color: "text-blue-400",
  },
  leo: {
    name: "Leo",
    symbol: "♌",
    element: "Fire",
    dates: "July 23 - August 22",
    traits: ["Creative", "Passionate", "Generous", "Warm-hearted"],
    compatibleSigns: ["Aries", "Sagittarius", "Gemini", "Libra"],
    luckyNumber: 1,
    color: "text-orange-400",
  },
  virgo: {
    name: "Virgo",
    symbol: "♍",
    element: "Earth",
    dates: "August 23 - September 22",
    traits: ["Loyal", "Analytical", "Kind", "Hardworking"],
    compatibleSigns: ["Taurus", "Capricorn", "Cancer", "Scorpio"],
    luckyNumber: 6,
    color: "text-emerald-400",
  },
  libra: {
    name: "Libra",
    symbol: "♎",
    element: "Air",
    dates: "September 23 - October 22",
    traits: ["Cooperative", "Diplomatic", "Gracious", "Fair-minded"],
    compatibleSigns: ["Gemini", "Aquarius", "Leo", "Sagittarius"],
    luckyNumber: 7,
    color: "text-pink-400",
  },
  scorpio: {
    name: "Scorpio",
    symbol: "♏",
    element: "Water",
    dates: "October 23 - November 21",
    traits: ["Resourceful", "Brave", "Passionate", "Stubborn"],
    compatibleSigns: ["Cancer", "Pisces", "Virgo", "Capricorn"],
    luckyNumber: 8,
    color: "text-purple-400",
  },
  sagittarius: {
    name: "Sagittarius",
    symbol: "♐",
    element: "Fire",
    dates: "November 22 - December 21",
    traits: ["Generous", "Idealistic", "Great sense of humor"],
    compatibleSigns: ["Aries", "Leo", "Libra", "Aquarius"],
    luckyNumber: 9,
    color: "text-indigo-400",
  },
  capricorn: {
    name: "Capricorn",
    symbol: "♑",
    element: "Earth",
    dates: "December 22 - January 19",
    traits: ["Responsible", "Disciplined", "Self-control", "Good managers"],
    compatibleSigns: ["Taurus", "Virgo", "Scorpio", "Pisces"],
    luckyNumber: 10,
    color: "text-gray-400",
  },
  aquarius: {
    name: "Aquarius",
    symbol: "♒",
    element: "Air",
    dates: "January 20 - February 18",
    traits: ["Progressive", "Original", "Independent", "Humanitarian"],
    compatibleSigns: ["Gemini", "Libra", "Aries", "Sagittarius"],
    luckyNumber: 11,
    color: "text-cyan-400",
  },
  pisces: {
    name: "Pisces",
    symbol: "♓",
    element: "Water",
    dates: "February 19 - March 20",
    traits: ["Compassionate", "Artistic", "Intuitive", "Gentle"],
    compatibleSigns: ["Cancer", "Scorpio", "Taurus", "Capricorn"],
    luckyNumber: 12,
    color: "text-teal-400",
  },
};
