export const SIGNS = [
  {
    id: "7f8ef3ea-4362-4a7d-8c56-4261b54ace8c",
    name: "Aries",
    element: "Fire",
    periodStart: "03-21",
    periodEnd: "04-19",
  },
  {
    id: "141a3999-293c-4962-86fe-02728dc86ea8",
    name: "Aquarius",
    element: "Air",
    periodStart: "01-20",
    periodEnd: "02-18",
  },
  {
    id: "63a10a90-35ee-4245-aad7-65f86c04897c",
    name: "Libra",
    element: "Air",
    periodStart: "09-23",
    periodEnd: "10-22",
  },
  {
    id: "e6bc92d8-85ef-4cf2-9cc9-d02c7a433af4",
    name: "Sagittarius",
    element: "Fire",
    periodStart: "11-22",
    periodEnd: "12-21",
  },
  {
    id: "b59e6e2a-f7ac-4cec-9c76-bcfe7922d06e",
    name: "Leo",
    element: "Fire",
    periodStart: "07-23",
    periodEnd: "08-22",
  },
  {
    id: "4500812e-b984-47c3-a04c-44bee362bac7",
    name: "Capricorn",
    element: "Earth",
    periodStart: "12-22",
    periodEnd: "01-19",
  },
  {
    id: "8126ccc0-a4b4-46ad-9f1d-7ecd42d91ea7",
    name: "Virgo",
    element: "Earth",
    periodStart: "08-23",
    periodEnd: "09-22",
  },
  {
    id: "2b87669d-0e85-4e4c-8e9e-f6e3a868c6d6",
    name: "Cancer",
    element: "Water",
    periodStart: "06-21",
    periodEnd: "07-22",
  },
  {
    id: "ca4343e6-0c14-4113-ba3a-b4016b4feffb",
    name: "Scorpio",
    element: "Water",
    periodStart: "10-23",
    periodEnd: "11-21",
  },
  {
    id: "861e2280-8c05-4a79-bd0c-a186e0fa2f7c",
    name: "Taurus",
    element: "Earth",
    periodStart: "04-20",
    periodEnd: "05-20",
  },
  {
    id: "95d0a5bc-482e-4f9f-ab8a-4b858794082c",
    name: "Gemini",
    element: "Air",
    periodStart: "05-21",
    periodEnd: "06-20",
  },
  {
    id: "faf2a44f-3b46-4e07-a888-ca6fd0be8639",
    name: "Pisces",
    element: "Water",
    periodStart: "02-19",
    periodEnd: "03-20",
  },
];
export const DECANS = [
  {
    signId: "7f8ef3ea-4362-4a7d-8c56-4261b54ace8c",
    decan: 1,
    periodStart: "03-21",
    periodEnd: "03-30",
    rulingPlanet: "Mars",
    description:
      "You’re a pure Aries, ruled by Mars. Bold, direct, and unstoppable—your energy can light up a room or lead an army.",
    traits: ["Bold", "Energetic", "Direct"],
  },
  {
    signId: "7f8ef3ea-4362-4a7d-8c56-4261b54ace8c",
    decan: 2,
    periodStart: "03-31",
    periodEnd: "04-09",
    rulingPlanet: "Sun",
    description:
      "You’re an Aries with Leo’s flair. You're fiery with a dramatic edge—courageous, charismatic, and full of prsignIde.",
    traits: ["Charismatic", "Proud", "Ambitious"],
  },
  {
    signId: "7f8ef3ea-4362-4a7d-8c56-4261b54ace8c",
    decan: 3,
    periodStart: "04-10",
    periodEnd: "04-19",
    rulingPlanet: "Jupiter",
    description:
      "You’re an adventurous Aries. Inspired and signIdealistic—you fight not just for glory, but for vision and meaning.",
    traits: ["Adventurous", "Idealistic", "Inspiring"],
  },
  {
    signId: "861e2280-8c05-4a79-bd0c-a186e0fa2f7c",
    decan: 1,
    periodStart: "04-20",
    periodEnd: "04-30",
    rulingPlanet: "Venus",
    description:
      "A classic Taurus—loyal, sensual, and grounded. You’re ruled by Venus, giving you a deep appreciation for comfort, beauty, and love.",
    traits: ["Grounded", "Sensual", "Loyal"],
  },
  {
    signId: "861e2280-8c05-4a79-bd0c-a186e0fa2f7c",
    decan: 2,
    periodStart: "05-01",
    periodEnd: "05-10",
    rulingPlanet: "Mercury",
    description:
      "You’re a detail-loving Taurus. Practical and smart—you blend sensual pleasures with clear logic and structure.",
    traits: ["Practical", "Detail-oriented", "Thoughtful"],
  },
  {
    signId: "861e2280-8c05-4a79-bd0c-a186e0fa2f7c",
    decan: 3,
    periodStart: "05-11",
    periodEnd: "05-20",
    rulingPlanet: "Saturn",
    description:
      "A disciplined Taurus. You’re ambitious and built for long-term success—calm under pressure and steady in pursuit.",
    traits: ["Disciplined", "Resilient", "Focused"],
  },
  {
    signId: "95d0a5bc-482e-4f9f-ab8a-4b858794082c",
    decan: 1,
    periodStart: "05-21",
    periodEnd: "05-31",
    rulingPlanet: "Mercury",
    description:
      "You’re pure Gemini—fast-talking, curious, and mentally alive. Your mind is always racing, and boredom is your only enemy.",
    traits: ["Curious", "Witty", "Expressive"],
  },
  {
    signId: "95d0a5bc-482e-4f9f-ab8a-4b858794082c",
    decan: 2,
    periodStart: "06-01",
    periodEnd: "06-10",
    rulingPlanet: "Venus",
    description:
      "A charming Gemini. You’re witty and refined, with a love of connection, style, and harmony in your social circles.",
    traits: ["Charming", "Social", "Balanced"],
  },
  {
    signId: "95d0a5bc-482e-4f9f-ab8a-4b858794082c",
    decan: 3,
    periodStart: "06-11",
    periodEnd: "06-20",
    rulingPlanet: "Uranus",
    description:
      "The rebel Gemini. You think outssignIde the box—innovative, unpredictable, and driven to challenge norms.",
    traits: ["Innovative", "Unpredictable", "Rebellious"],
  },
  {
    signId: "2b87669d-0e85-4e4c-8e9e-f6e3a868c6d6",
    decan: 1,
    periodStart: "06-21",
    periodEnd: "07-01",
    rulingPlanet: "Moon",
    description:
      "You’re a true Cancer—nurturing, protective, deeply emotional. You feel what others miss and care with full heart.",
    traits: ["Nurturing", "Emotional", "Protective"],
  },
  {
    signId: "2b87669d-0e85-4e4c-8e9e-f6e3a868c6d6",
    decan: 2,
    periodStart: "07-02",
    periodEnd: "07-11",
    rulingPlanet: "Pluto",
    description:
      "Intense and secretive. You’re emotionally deep and intuitively powerful—people confsignIde in you without knowing why.",
    traits: ["Intuitive", "Private", "Deep"],
  },
  {
    signId: "2b87669d-0e85-4e4c-8e9e-f6e3a868c6d6",
    decan: 3,
    periodStart: "07-12",
    periodEnd: "07-22",
    rulingPlanet: "Neptune",
    description:
      "The dreamy Cancer. Romantic, creative, and gentle—your compassion flows like water.",
    traits: ["Dreamy", "Gentle", "Compassionate"],
  },
  {
    signId: "b59e6e2a-f7ac-4cec-9c76-bcfe7922d06e",
    decan: 1,
    periodStart: "07-23",
    periodEnd: "08-01",
    rulingPlanet: "Sun",
    description:
      "You are Leo in its pure form—radiant, proud, born to lead. You shine without trying and inspire by being you.",
    traits: ["Radiant", "ConfsignIdent", "Leader"],
  },
  {
    signId: "b59e6e2a-f7ac-4cec-9c76-bcfe7922d06e",
    decan: 2,
    periodStart: "08-02",
    periodEnd: "08-11",
    rulingPlanet: "Jupiter",
    description:
      "A visionary Leo. You dream big and love freedom—you’re warm-hearted and always looking toward the horizon.",
    traits: ["Visionary", "Warm-hearted", "Generous"],
  },
  {
    signId: "b59e6e2a-f7ac-4cec-9c76-bcfe7922d06e",
    decan: 3,
    periodStart: "08-12",
    periodEnd: "08-22",
    rulingPlanet: "Mars",
    description:
      "The warrior Leo. Energetic, bold, and assertive—you command attention and aren’t afrasignId of challenge.",
    traits: ["Assertive", "Courageous", "Bold"],
  },
  {
    signId: "8126ccc0-a4b4-46ad-9f1d-7ecd42d91ea7",
    decan: 1,
    periodStart: "08-23",
    periodEnd: "09-01",
    rulingPlanet: "Mercury",
    description:
      "A classic Virgo—sharp, humble, and efficient. You notice what others miss and fix what’s broken.",
    traits: ["Precise", "Helpful", "Observant"],
  },
  {
    signId: "8126ccc0-a4b4-46ad-9f1d-7ecd42d91ea7",
    decan: 2,
    periodStart: "09-02",
    periodEnd: "09-11",
    rulingPlanet: "Saturn",
    description:
      "The planner Virgo. You’re structured and serious, blending Virgo’s precision with Capricorn’s discipline.",
    traits: ["Organized", "Serious", "Disciplined"],
  },
  {
    signId: "8126ccc0-a4b4-46ad-9f1d-7ecd42d91ea7",
    decan: 3,
    periodStart: "09-12",
    periodEnd: "09-22",
    rulingPlanet: "Venus",
    description:
      "The soft Virgo. You’re thoughtful and romantic—bringing beauty and heart into practical spaces.",
    traits: ["Romantic", "Artistic", "Kind"],
  },
  {
    signId: "63a10a90-35ee-4245-aad7-65f86c04897c",
    decan: 1,
    periodStart: "09-23",
    periodEnd: "10-02",
    rulingPlanet: "Venus",
    description:
      "A pure Libra—graceful, social, and balanced. You live for peace, art, and meaningful partnership.",
    traits: ["Graceful", "Fair", "Diplomatic"],
  },
  {
    signId: "63a10a90-35ee-4245-aad7-65f86c04897c",
    decan: 2,
    periodStart: "10-03",
    periodEnd: "10-12",
    rulingPlanet: "Uranus",
    description:
      "The thinker Libra. Original, fair, and progressive—your sense of justice goes beyond the surface.",
    traits: ["Progressive", "Inventive", "Unconventional"],
  },
  {
    signId: "63a10a90-35ee-4245-aad7-65f86c04897c",
    decan: 3,
    periodStart: "10-13",
    periodEnd: "10-22",
    rulingPlanet: "Mercury",
    description:
      "The communicator Libra. You blend charm with intellect—naturally expressive and always curious.",
    traits: ["Communicative", "Witty", "Adaptable"],
  },
  {
    signId: "ca4343e6-0c14-4113-ba3a-b4016b4feffb",
    decan: 1,
    periodStart: "10-23",
    periodEnd: "11-01",
    rulingPlanet: "Pluto",
    description:
      "Classic Scorpio—intense, deep, and magnetic. You see through people and hold powerful emotional depth.",
    traits: ["Intense", "Focused", "Magnetic"],
  },
  {
    signId: "ca4343e6-0c14-4113-ba3a-b4016b4feffb",
    decan: 2,
    periodStart: "11-02",
    periodEnd: "11-11",
    rulingPlanet: "Neptune",
    description:
      "The dreamer Scorpio. Empathic and mysterious, your emotions are layered with imagination and sensitivity.",
    traits: ["Empathic", "Mysterious", "Spiritual"],
  },
  {
    signId: "ca4343e6-0c14-4113-ba3a-b4016b4feffb",
    decan: 3,
    periodStart: "11-12",
    periodEnd: "11-21",
    rulingPlanet: "Moon",
    description:
      "The nurturing Scorpio. Protective and emotionally loyal—you love deeply and shield those close.",
    traits: ["Protective", "Loyal", "Emotional"],
  },
  {
    signId: "e6bc92d8-85ef-4cf2-9cc9-d02c7a433af4",
    decan: 1,
    periodStart: "11-22",
    periodEnd: "12-01",
    rulingPlanet: "Jupiter",
    description:
      "You are Sagittarius at its boldest—optimistic, open-minded, and always seeking truth and adventure.",
    traits: ["Optimistic", "Philosophical", "Adventurous"],
  },
  {
    signId: "e6bc92d8-85ef-4cf2-9cc9-d02c7a433af4",
    decan: 2,
    periodStart: "12-02",
    periodEnd: "12-11",
    rulingPlanet: "Mars",
    description:
      "The go-getter Sagittarius. Energetic, direct, and assertive—you act fast and follow passion.",
    traits: ["Energetic", "Independent", "Driven"],
  },
  {
    signId: "e6bc92d8-85ef-4cf2-9cc9-d02c7a433af4",
    decan: 3,
    periodStart: "12-12",
    periodEnd: "12-21",
    rulingPlanet: "Sun",
    description:
      "The expressive Sagittarius. Warm, creative, and self-confsignIdent—your light inspires those around you.",
    traits: ["Creative", "Expressive", "Self-assured"],
  },
  {
    signId: "4500812e-b984-47c3-a04c-44bee362bac7",
    decan: 1,
    periodStart: "12-22",
    periodEnd: "12-31",
    rulingPlanet: "Saturn",
    description:
      "True Capricorn—disciplined, wise, and patient. You value growth that lasts and lead with quiet strength.",
    traits: ["Disciplined", "Ambitious", "Grounded"],
  },
  {
    signId: "4500812e-b984-47c3-a04c-44bee362bac7",
    decan: 2,
    periodStart: "01-01",
    periodEnd: "01-10",
    rulingPlanet: "Venus",
    description:
      "The refined Capricorn. Practical but also sensuous—you find beauty in structure and peace in planning.",
    traits: ["Elegant", "Practical", "Peaceful"],
  },
  {
    signId: "4500812e-b984-47c3-a04c-44bee362bac7",
    decan: 3,
    periodStart: "01-11",
    periodEnd: "01-19",
    rulingPlanet: "Mercury",
    description:
      "The analytical Capricorn. Detail-oriented, sharp, and focused—you build success step-by-step.",
    traits: ["Strategic", "Analytical", "Reliable"],
  },
  {
    signId: "141a3999-293c-4962-86fe-02728dc86ea8",
    decan: 1,
    periodStart: "01-20",
    periodEnd: "01-29",
    rulingPlanet: "Uranus",
    description:
      "Pure Aquarius—visionary, independent, and future-minded. You’re original and a true signIdea person.",
    traits: ["Innovative", "Visionary", "Independent"],
  },
  {
    signId: "141a3999-293c-4962-86fe-02728dc86ea8",
    decan: 2,
    periodStart: "01-30",
    periodEnd: "02-08",
    rulingPlanet: "Mercury",
    description:
      "The brainy Aquarius. Fast-talking and inventive—you blend logic with creativity in unique ways.",
    traits: ["Intelligent", "Logical", "Inventive"],
  },
  {
    signId: "141a3999-293c-4962-86fe-02728dc86ea8",
    decan: 3,
    periodStart: "02-09",
    periodEnd: "02-18",
    rulingPlanet: "Venus",
    description:
      "The graceful Aquarius. Socially aware, stylish, and just—you bring fairness to friendship and love.",
    traits: ["Stylish", "Friendly", "Idealistic"],
  },
  {
    signId: "faf2a44f-3b46-4e07-a888-ca6fd0be8639",
    decan: 1,
    periodStart: "02-19",
    periodEnd: "02-28",
    rulingPlanet: "Neptune",
    description:
      "You’re Pisces at heart—dreamy, empathic, and imaginative. You feel the world deeply and live in color.",
    traits: ["Imaginative", "Empathic", "Dreamy"],
  },
  {
    signId: "faf2a44f-3b46-4e07-a888-ca6fd0be8639",
    decan: 2,
    periodStart: "03-01",
    periodEnd: "03-10",
    rulingPlanet: "Moon",
    description:
      "The nurturing Pisces. Gentle and protective—you care for others like family, no matter who they are.",
    traits: ["Compassionate", "Gentle", "Supportive"],
  },
  {
    signId: "faf2a44f-3b46-4e07-a888-ca6fd0be8639",
    decan: 3,
    periodStart: "03-11",
    periodEnd: "03-20",
    rulingPlanet: "Pluto",
    description:
      "The mystic Pisces. Intense and spiritual—you’re drawn to the unknown and the transformative.",
    traits: ["Introspective", "Transformative", "Spiritual"],
  },
];
