name: Next.js CI with Bun

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install dependencies
        run: bun install

      - name: Lint Next.js app
        run: bun run lint

      - name: Run tests
        run: bun test

      - name: Build the project
        run: bun run build
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          BETTER_AUTH_SECRET: ${{secrets.BETTER_AUTH_SECRET}}
          BETTER_AUTH_URL: ${{secrets.BETTER_AUTH_URL}}
          RESEND_API_KEY: ${{secrets.RESEND_API_KEY}}